workflows:
  ios-keyboard:
    name: iOS Keyboard Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      node: latest
      cocoapods: default
    scripts:
      - name: Install XcodeGen
        script: |
          #!/usr/bin/env bash
          set -e
          brew install xcodegen
      - name: Generate Xcode project
        script: |
          #!/usr/bin/env bash
          set -e
          xcodegen generate
      - name: Install dependencies
        script: |
          #!/usr/bin/env bash
          set -e
          pod install
      - name: Build iOS app
        script: |
          #!/usr/bin/env bash
          set -e
          xcodebuild build-for-distribution \
            -workspace Keyboard.xcworkspace \
            -scheme Keyboard \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath $CM_BUILD_DIR/Keyboard.xcarchive
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - user@example.com # Replace with your email 