name: Keyboard
options:
  bundleIdPrefix: com.keyboard
  deploymentTarget:
    iOS: 15.0

targets:
  KeyboardHost:
    type: application
    platform: iOS
    sources:
      - KeyboardHost
    settings:
      base:
        INFOPLIST_FILE: KeyboardHost/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.keyboard.host
    info:
      path: KeyboardHost/Info.plist
      properties:
        CFBundleDisplayName: Keyboard Host
        CFBundleIdentifier: com.keyboard.host
        CFBundleName: KeyboardHost
        CFBundlePackageType: APPL
        CFBundleShortVersionString: 1.0.0
        CFBundleVersion: 1
        UILaunchStoryboardName: LaunchScreen
        UIMainStoryboardFile: Main
    dependencies:
      - target: Keyboard

  Keyboard:
    type: app-extension
    platform: iOS
    sources:
      - Keyboard
    settings:
      base:
        INFOPLIST_FILE: Keyboard/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.keyboard.keyboard
    info:
      path: Keyboard/Info.plist
      properties:
        CFBundleDisplayName: Keyboard
        CFBundleIdentifier: com.keyboard.keyboard
        CFBundleName: Keyboard
        CFBundlePackageType: XPC!
        CFBundleShortVersionString: 1.0.0
        CFBundleVersion: 1
        NSExtension:
          NSExtensionAttributes:
            IsASCIICapable: true
            NeedsInputModeSwitchKey: true
            PrimaryLanguage: en-US
          NSExtensionPointIdentifier: com.apple.keyboard-service 