name: ArabicKeyboard
options:
  bundleIdPrefix: com.arabickeyboard
  deploymentTarget:
    iOS: 15.0
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

targets:
  KeyboardHost:
    type: application
    platform: iOS
    sources:
      - path: KeyboardHost
        excludes:
          - "*.md"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.arabickeyboard.host
        DEVELOPMENT_TEAM: ""  # Добавьте ваш Development Team ID если есть
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: Automatic
    dependencies:
      - target: Keyboard
    info:
      path: KeyboardHost/Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
        LSRequiresIPhoneOS: true

  Keyboard:
    type: app-extension
    platform: iOS
    sources:
      - path: Keyboard
        excludes:
          - "*.md"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.arabickeyboard.keyboard
        DEVELOPMENT_TEAM: ""  # Добавьте ваш Development Team ID если есть
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: Automatic
    dependencies:
      - sdk: Foundation.framework
      - sdk: UIKit.framework
    info:
      path: Keyboard/Info.plist 